engines:
  tslint:
    enabled: true
    channel: beta
    config: tslint.json
  csslint:
    enabled: true
ratings:
  paths:
    - "**.css"
    - "**.ts"
exclude_paths:
  - bin
  - node_modules
  - typings
  - coverage
  - dist
  - e2e
  - .vscode